Add docker
PavelIgK/java-shareit pull request #4
Opened 2024-01-30 18:24 UTC by PavelIgK

2024-01-31 11:16 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/booking/model/Booking.java
Для сущностей @Data использовать не рекомендуется, т.к. @Data генерирует equals и hashCode на основе всех полей, а у нас сущность однозначно идентифицируется id который генерится в БД.
В данной работе ничего страшного не произойдет, но лучше не привыкать). Если бы добавили кэширование, то возникли бы проблемы.
https://stackoverflow.com/questions/75181366/why-jpa-buddy-complains-about-data-annotation-over-jpa-entity

2024-01-31 11:21 UTC, VadimZharkov requested changes
Можно улучшить.

2024-01-31 13:51 UTC, PavelIgK commented on server/src/main/java/ru/practicum/shareit/booking/model/Booking.java
Спасибо, добавил @EqualsAndHashCode(of = {"id"}).

2024-01-31 14:06 UTC, PavelIgK commented on server/src/main/java/ru/practicum/shareit/booking/model/Booking.java
Добавил еще @ToString(exclude = {...})

2024-02-01 07:36 UTC, VadimZharkov approved these changes

2024-02-01 08:42 UTC, merged